runfolder: "/data/NC_projects/4767_KDePaepe_PacBio"
movie: "m64279e_240524_094336"
adapterfolder: "bcM0002--bcM0002"
samplesheet: "Exp4767_SMRTLink_Barcodefile.csv"
outfolder: "/data/NC_projects/4767_KDePaepe_PacBio/demux_results"
qc_format: "html"
inputs: "inputs"
skera_results: "skera_results"
lima_results: "lima_results"
fastq_results: "fastq_results"
log_skera: "INFO"
log_lima: "INFO"
nthr_skera: 48
nthr_lima: 48
par_bam2fastq: 12
nthr_bam2fastq: 4
mincnt: 12000
final_results: "final_results"
