name: pb-16s-nf_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - nextflow
  - r-base
  - r-essentials
  - r-rmarkdown
  - r-readr
  - r-treemap
  - r-ggplot2
  - r-knitr
  - r-kableExtra
  - r-dplyr
  - r-stringr
  - r-tidyr
  - r-ape
